wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718184084
    t:
      1:
      - 1
      - 50
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.17.1
      8:
      - 5
      13: darwin-x86_64
