
env : &env LunarLander-v2
trainer : &trainer basic
model : &model small

# Logging
do_wandb : False
wandb_config:
  project : DeepRL_test



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - envs : *env
  - trainers : *trainer
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 



# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .