
env : "CartPole-v1" #ALE/SpaceInvaders-v5 #CartPole-v1 #CarRacing-v2

# Continuous action space for some environments
continuous : False

trainer : &trainer ppo
network : &network linear


number_of_environments : 1 # If parallel selected

# Logging
do_wandb : False
wandb_config:
  project : DeepRL_test

# Wrappers to use (will not use them if not compatible with the environment)
wrappers :

  RepeatActionV0 :
    number_of_repeats : 0

  SpaceInvadersWrapper :
    death_penalty : -30
    missile_penalty : -1 # Useless missiles can't be detected
  
  BreakoutWrapper :
    nothing : 4
  
  HistoryWrapper :
    n_history : 4
  


# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - trainers : *trainer
  - networks : *network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .