
env : CarRacing-v2

# Continuous action space for some environments
continuous : False

trainer : &trainer basic
network : &network cnn

# Logging
do_wandb : True
wandb_config:
  project : DeepRL_test



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - trainers : *trainer
  - networks : *network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .