
env : ALE/SpaceInvaders-v5 #CartPole-v1 #CarRacing-v2

# Continuous action space for some environments
continuous : False

trainer : &trainer basic
network : &network cnn_space_invaders


number_of_environments : 2 # If parallel selected

# Logging
do_wandb : False
wandb_config:
  project : DeepRL_test

# Wrappers to use (will not use them if not compatible with the environment)
wrappers : 

  RepeatActionV0 :
    number_of_repeats : 0

  SpaceInvadersWrapper :
    penalty : -1

# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - trainers : *trainer
  - networks : *network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .